spring.application.name=habit-tracker-api

server.port=${PORT:8080}



spring.r2dbc.url=${DATABASE_URL:r2dbc:postgresql://localhost:5435/habit_db}
spring.r2dbc.username=${DATABASE_USERNAME:postgres}
spring.r2dbc.password=${DATABASE_PASSWORD:postgres}
